/** CEFR A1–C2 vocabulary in small teach-then-quiz stages. */

function pack(id, title, subtitle, items, extra = {}) {
  return {
    id,
    title,
    subtitle,
    teach: extra.teach || (items.length > 8 ? 'grid' : 'cards'),
    intro: Boolean(extra.intro),
    mix: Boolean(extra.mix),
    chars: items.map(([char, romaji, meaning]) => ({
      char,
      romaji,
      meaning,
      hint: '',
    })),
  };
}

function mix(id, title) {
  return pack(id, title, 'Everything in this level, shuffled.', [], { teach: 'grid', mix: true });
}

export const VOCAB_SCRIPTS = {
  a1: {
    id: 'a1',
    label: 'A1 words',
    kicker: 'CEFR · Basic user',
    blurb: 'Breakthrough German: greetings, people, time, food, and everyday verbs (Goethe-A1 style).',
    kind: 'vocab',
    group: 'words',
    stages: [
      pack(
        'a1-0',
        'Stage 0 · First words',
        'Six everyday words. See the writing, the sound, and the English meaning, then pick them from A–F.',
        [
          ['ich', 'ikh', 'I'],
          ['Deutschland', 'doytsh-lahnt', 'Germany'],
          ['der Mensch', 'der mensh', 'person / human'],
          ['das Wasser', 'dahs vah-ser', 'water'],
          ['essen', 'ess-en', 'to eat'],
          ['gehen', 'gay-en', 'to go'],
        ],
        { intro: true }
      ),
      pack('a1-1', 'Stage 1 · Greetings', 'Hello, thanks, yes, no, please.', [
        ['Hallo', 'hah-lo', 'hello'],
        ['Guten Tag', 'goo-ten tahk', 'good day'],
        ['Guten Morgen', 'goo-ten mor-gen', 'good morning'],
        ['Danke', 'dahn-kuh', 'thank you'],
        ['Bitte', 'bit-tuh', 'please / you’re welcome'],
        ['Entschuldigung', 'ent-shool-dee-goong', 'excuse me / sorry'],
        ['Ja', 'yah', 'yes'],
        ['Nein', 'nine', 'no'],
        ['Auf Wiedersehen', 'owf vee-der-zay-en', 'goodbye'],
        ['Tschüss', 'chüss', 'bye (informal)'],
      ]),
      pack('a1-2', 'Stage 2 · People', 'Family, friends, school roles.', [
        ['du', 'doo', 'you (informal)'],
        ['Sie', 'zee', 'you (formal)'],
        ['er', 'air', 'he'],
        ['sie', 'zee', 'she / they'],
        ['wir', 'veer', 'we'],
        ['der Freund', 'der froynt', 'friend (male) / boyfriend'],
        ['die Freundin', 'dee froynt-in', 'friend (female) / girlfriend'],
        ['die Familie', 'dee fah-mee-lee-uh', 'family'],
        ['die Mutter', 'dee moo-ter', 'mother'],
        ['der Vater', 'der fah-ter', 'father'],
        ['das Kind', 'dahs kint', 'child'],
      ]),
      pack('a1-3', 'Stage 3 · Time', 'Today, tomorrow, hours, every day.', [
        ['heute', 'hoy-tuh', 'today'],
        ['morgen', 'mor-gen', 'tomorrow / morning'],
        ['gestern', 'ges-tern', 'yesterday'],
        ['jetzt', 'yetst', 'now'],
        ['die Uhr', 'dee oor', 'clock / o’clock'],
        ['die Minute', 'dee mee-noo-tuh', 'minute'],
        ['die Woche', 'dee vokh-uh', 'week'],
        ['das Jahr', 'dahs yahr', 'year'],
        ['der Tag', 'der tahk', 'day'],
        ['immer', 'im-mer', 'always'],
      ]),
      pack('a1-4', 'Stage 4 · Core verbs', 'Be, have, come, see, speak.', [
        ['sein', 'zine', 'to be'],
        ['haben', 'hah-ben', 'to have'],
        ['kommen', 'kom-men', 'to come'],
        ['sehen', 'zay-en', 'to see'],
        ['sprechen', 'shprekh-en', 'to speak'],
        ['trinken', 'trink-en', 'to drink'],
        ['kaufen', 'kow-fen', 'to buy'],
        ['warten', 'var-ten', 'to wait'],
        ['wohnen', 'voh-nen', 'to live (reside)'],
        ['heißen', 'hy-sen', 'to be called'],
      ]),
      pack('a1-5', 'Stage 5 · Adjectives', 'Big, small, hot, cheap, good.', [
        ['groß', 'grohs', 'big / tall'],
        ['klein', 'kline', 'small'],
        ['neu', 'noy', 'new'],
        ['alt', 'ahlt', 'old'],
        ['teuer', 'toy-er', 'expensive'],
        ['billig', 'bill-ikh', 'cheap'],
        ['gut', 'goot', 'good'],
        ['schlecht', 'shlekht', 'bad'],
        ['heiß', 'hice', 'hot'],
        ['kalt', 'kahlt', 'cold'],
      ]),
      pack('a1-6', 'Stage 6 · Places', 'School, station, home, shop.', [
        ['die Schule', 'dee shoo-luh', 'school'],
        ['das Haus', 'dahs hows', 'house'],
        ['der Bahnhof', 'der bahn-hohf', 'train station'],
        ['das Geschäft', 'dahs ge-sheft', 'shop'],
        ['das Krankenhaus', 'dahs krank-en-hows', 'hospital'],
        ['die Firma', 'dee fir-ma', 'company'],
        ['das Land', 'dahs lahnt', 'country / land'],
        ['die Stadt', 'dee shtat', 'city'],
        ['das Zimmer', 'dahs tsim-mer', 'room'],
        ['die Toilette', 'dee toa-let-uh', 'toilet'],
      ]),
      pack('a1-7', 'Stage 7 · Food', 'Meals and drinks you use every day.', [
        ['das Brot', 'dahs broht', 'bread'],
        ['der Apfel', 'der ap-fel', 'apple'],
        ['der Kaffee', 'der kah-fay', 'coffee'],
        ['der Tee', 'der tay', 'tea'],
        ['das Fleisch', 'dahs flysh', 'meat'],
        ['der Fisch', 'der fish', 'fish'],
        ['das Gemüse', 'dahs ge-mü-zuh', 'vegetables'],
        ['das Obst', 'dahs ohpst', 'fruit'],
        ['die Milch', 'dee milkh', 'milk'],
        ['das Frühstück', 'dahs frü-shtük', 'breakfast'],
      ]),
      pack('a1-8', 'Stage 8 · Everyday', 'Book, car, weather, question words.', [
        ['das Buch', 'dahs bookh', 'book'],
        ['das Auto', 'dahs ow-to', 'car'],
        ['das Telefon', 'dahs tel-e-fohn', 'telephone'],
        ['das Wetter', 'dahs vet-ter', 'weather'],
        ['der Regen', 'der ray-gen', 'rain'],
        ['der Name', 'der nah-muh', 'name'],
        ['was', 'vahs', 'what'],
        ['wer', 'vair', 'who'],
        ['wo', 'voh', 'where'],
        ['warum', 'vah-room', 'why'],
      ]),
      pack('a1-9', 'Stage 9 · More verbs', 'Read, write, sleep, learn, work.', [
        ['lesen', 'lay-zen', 'to read'],
        ['schreiben', 'shry-ben', 'to write'],
        ['schlafen', 'shlah-fen', 'to sleep'],
        ['aufstehen', 'owf-shtay-en', 'to get up'],
        ['arbeiten', 'ar-by-ten', 'to work'],
        ['lernen', 'lair-nen', 'to learn'],
        ['fahren', 'fah-ren', 'to drive / go (by vehicle)'],
        ['machen', 'makh-en', 'to do / make'],
        ['finden', 'fin-den', 'to find'],
        ['brauchen', 'brow-khen', 'to need'],
      ]),
      pack('a1-10', 'Stage 10 · Amount & extras', 'A little, a lot, already, very.', [
        ['eins', 'ines', 'one'],
        ['zwei', 'tsvy', 'two'],
        ['ein bisschen', 'ine biss-khen', 'a little'],
        ['viel', 'feel', 'a lot / much'],
        ['alles', 'ah-less', 'everything'],
        ['schon', 'shohn', 'already'],
        ['noch', 'nokh', 'still / yet'],
        ['sehr', 'zair', 'very'],
        ['nicht', 'nikht', 'not'],
        ['kein Problem', 'kine pro-blaym', 'no problem'],
      ]),
      mix('a1-mix', 'Stage 11 · A1 mixed review'),
    ],
  },
  a2: {
    id: 'a2',
    label: 'A2 words',
    kicker: 'CEFR · Basic user',
    blurb: 'Waystage German: plans, travel, feelings, work, and useful everyday verbs.',
    kind: 'vocab',
    group: 'words',
    stages: [
      pack(
        'a2-0',
        'Stage 0 · First A2',
        'Six high-frequency A2 words. Learn them, then tap A–F.',
        [
          ['der Plan', 'der plahn', 'plan'],
          ['das Versprechen', 'dahs fer-shprekh-en', 'promise'],
          ['die Vorbereitung', 'dee for-be-ry-toong', 'preparation'],
          ['wichtig', 'vikh-tikh', 'important'],
          ['möglich', 'mög-likh', 'possible'],
          ['die Bedeutung', 'dee be-doy-toong', 'meaning'],
        ],
        { intro: true }
      ),
      pack('a2-1', 'Stage 1 · Think & decide', 'Know, forget, begin, choose.', [
        ['denken', 'denk-en', 'to think'],
        ['wissen', 'viss-en', 'to know (a fact)'],
        ['verstehen', 'fer-shtay-en', 'to understand'],
        ['erklären', 'er-klair-en', 'to explain'],
        ['vergessen', 'fer-gess-en', 'to forget'],
        ['beginnen', 'be-gin-nen', 'to begin'],
        ['enden', 'en-den', 'to end'],
        ['weitermachen', 'vy-ter-makh-en', 'to continue'],
        ['entscheiden', 'ent-shy-den', 'to decide'],
        ['wählen', 'vail-en', 'to choose'],
      ]),
      pack('a2-2', 'Stage 2 · Plans & reasons', 'Experience, reason, situation.', [
        ['die Erfahrung', 'dee er-fah-roong', 'experience'],
        ['der Grund', 'der groont', 'reason'],
        ['die Situation', 'dee zee-too-ah-tsyohn', 'situation'],
        ['die Erklärung', 'dee er-klair-oong', 'explanation'],
        ['die Meinung', 'dee my-noong', 'opinion'],
        ['die Frage', 'dee frah-guh', 'question'],
        ['die Antwort', 'dee ant-vort', 'answer'],
        ['das Problem', 'dahs pro-blaym', 'problem'],
        ['einfach', 'ine-fakh', 'simple / easy'],
        ['kompliziert', 'kom-plee-tseert', 'complicated'],
      ]),
      pack('a2-3', 'Stage 3 · Travel', 'Airport, ticket, reservation, luggage.', [
        ['die Reise', 'dee ry-zuh', 'trip / journey'],
        ['der Flughafen', 'der floog-hah-fen', 'airport'],
        ['die Karte', 'dee kar-tuh', 'map / ticket / card'],
        ['das Ticket', 'dahs tik-et', 'ticket'],
        ['die Reservierung', 'dee re-zer-veer-oong', 'reservation'],
        ['das Gepäck', 'dahs ge-peck', 'luggage'],
        ['die Landschaft', 'dee lahnt-shahft', 'landscape'],
        ['das Gebäude', 'dahs ge-boy-duh', 'building'],
        ['die Adresse', 'dee ah-dress-uh', 'address'],
        ['gegenüber', 'gay-gen-ü-ber', 'opposite / across from'],
      ]),
      pack('a2-4', 'Stage 4 · Feelings', 'Worry, kind, embarrassed, enough.', [
        ['das Gefühl', 'dahs ge-fül', 'feeling'],
        ['die Sorge', 'dee zor-guh', 'worry'],
        ['ruhig', 'roo-ikh', 'calm'],
        ['schade', 'shah-duh', 'a pity / too bad'],
        ['peinlich', 'pine-likh', 'embarrassing'],
        ['nett', 'net', 'nice / kind'],
        ['streng', 'shtreng', 'strict'],
        ['richtig', 'rikh-tikh', 'correct'],
        ['genug', 'ge-nook', 'enough'],
        ['kaputt', 'kah-putt', 'broken'],
      ]),
      pack('a2-5', 'Stage 5 · Work & contact', 'Meeting, salary, reply, late.', [
        ['die Besprechung', 'dee be-shprekh-oong', 'meeting'],
        ['das Gehalt', 'dahs ge-halt', 'salary'],
        ['die Nachricht', 'dee nakh-rikht', 'message'],
        ['der Kontakt', 'der kon-takt', 'contact'],
        ['ankommen', 'an-kom-men', 'to arrive'],
        ['sich verspäten', 'zikh fer-shpait-en', 'to be late'],
        ['rechtzeitig', 'rekht-tsy-tikh', 'on time'],
        ['sich beeilen', 'zikh be-eye-len', 'to hurry'],
        ['bleiben', 'bly-ben', 'to stay / remain'],
        ['der Angestellte', 'der an-ge-shtel-tuh', 'employee'],
      ]),
      pack('a2-6', 'Stage 6 · Body & daily life', 'Health, clothes, housework.', [
        ['die Krankheit', 'dee krank-hite', 'illness'],
        ['gesund', 'ge-zoont', 'healthy'],
        ['weh tun', 'vay toon', 'to hurt'],
        ['müde', 'mü-duh', 'tired'],
        ['die Kleidung', 'dee kly-doong', 'clothes'],
        ['waschen', 'vash-en', 'to wash'],
        ['aufräumen', 'owf-roy-men', 'to tidy up'],
        ['wegwerfen', 'vek-ver-fen', 'to throw away'],
        ['öffnen', 'öf-nen', 'to open'],
        ['schließen', 'shlee-sen', 'to close'],
      ]),
      pack('a2-7', 'Stage 7 · More A2 verbs', 'Help, move, change, notice.', [
        ['helfen', 'hel-fen', 'to help'],
        ['unterstützen', 'oon-ter-shtüts-en', 'to support'],
        ['sich bewegen', 'zikh be-vay-gen', 'to move'],
        ['sich ändern', 'zikh en-dern', 'to change'],
        ['bemerken', 'be-merk-en', 'to notice'],
        ['finden', 'fin-den', 'to find'],
        ['suchen', 'zookh-en', 'to search for'],
        ['bringen', 'bring-en', 'to bring / deliver'],
        ['leihen', 'ly-en', 'to borrow / lend'],
        ['besuchen', 'be-zookh-en', 'to visit'],
      ]),
      mix('a2-mix', 'Stage 8 · A2 mixed review'),
    ],
  },
  b1: {
    id: 'b1',
    label: 'B1 words',
    kicker: 'CEFR · Independent',
    blurb: 'Threshold German: society, results, methods, and verbs of thinking (Goethe-B1 style).',
    kind: 'vocab',
    group: 'words',
    stages: [
      pack(
        'b1-0',
        'Stage 0 · First B1',
        'Six common B1 words from news and daily argument.',
        [
          ['die Beziehung', 'dee be-tsee-oong', 'relationship / connection'],
          ['die Gesellschaft', 'dee ge-zel-shahft', 'society'],
          ['eigentlich', 'eye-gent-likh', 'actually / in fact'],
          ['notwendig', 'note-ven-dikh', 'necessary'],
          ['die Information', 'dee in-for-mah-tsyohn', 'information'],
          ['die Methode', 'dee me-toh-duh', 'method / way'],
        ],
        { intro: true }
      ),
      pack('b1-1', 'Stage 1 · Society', 'Economy, culture, environment, history.', [
        ['die Wirtschaft', 'dee virt-shahft', 'economy'],
        ['die Politik', 'dee po-lee-teek', 'politics'],
        ['die Umwelt', 'dee oom-velt', 'environment'],
        ['die Technik', 'dee tekh-neek', 'technology / technique'],
        ['die Kultur', 'dee kool-toor', 'culture'],
        ['die Geschichte', 'dee ge-shikh-tuh', 'history / story'],
        ['die Bildung', 'dee bild-oong', 'education'],
        ['international', 'in-ter-nah-tsyo-nahl', 'international'],
        ['die Sicherheit', 'dee zikh-er-hite', 'safety / security'],
        ['der Frieden', 'der free-den', 'peace'],
      ]),
      pack('b1-2', 'Stage 2 · Ideas', 'Cause, result, purpose, condition.', [
        ['die Gelegenheit', 'dee ge-lay-gen-hite', 'opportunity'],
        ['der Einfluss', 'der ine-flooss', 'influence'],
        ['die Bedingung', 'dee be-ding-oong', 'condition'],
        ['das Ergebnis', 'dahs er-geb-niss', 'result'],
        ['die Ursache', 'dee oor-zakh-uh', 'cause'],
        ['das Ziel', 'dahs tseel', 'goal / purpose'],
        ['der Inhalt', 'der in-halt', 'contents'],
        ['der Zustand', 'der tsoo-shtahnt', 'state / condition'],
        ['der Zeitraum', 'der tsite-rowm', 'period of time'],
        ['falls', 'fahls', 'in case / if'],
      ]),
      pack('b1-3', 'Stage 3 · Action nouns', 'Success, effort, change, report.', [
        ['die Teilnahme', 'dee tile-nah-muh', 'participation'],
        ['der Erfolg', 'der er-folk', 'success'],
        ['der Misserfolg', 'der miss-er-folk', 'failure'],
        ['die Anstrengung', 'dee an-streng-oong', 'effort'],
        ['das Wachstum', 'dahs vakhs-toom', 'growth'],
        ['die Veränderung', 'dee fer-en-de-roong', 'change'],
        ['die Entwicklung', 'dee ent-vik-loong', 'development'],
        ['die Lösung', 'dee lös-oong', 'solution'],
        ['die Bestätigung', 'dee be-shtait-ee-goong', 'confirmation'],
        ['der Bericht', 'der be-rikht', 'report'],
      ]),
      pack('b1-4', 'Stage 4 · Think verbs', 'Consider, investigate, compare.', [
        ['fühlen', 'fü-len', 'to feel'],
        ['überlegen', 'ü-ber-lay-gen', 'to consider / think over'],
        ['untersuchen', 'oon-ter-zookh-en', 'to investigate / examine'],
        ['vergleichen', 'fer-gly-khen', 'to compare'],
        ['glauben', 'glow-ben', 'to believe'],
        ['zweifeln', 'tsvy-feln', 'to doubt'],
        ['erwarten', 'er-var-ten', 'to expect'],
        ['beurteilen', 'be-oor-tye-len', 'to judge / assess'],
        ['beschreiben', 'be-shry-ben', 'to describe'],
        ['vorstellen', 'for-shtel-len', 'to introduce / imagine'],
      ]),
      pack('b1-5', 'Stage 5 · Change verbs', 'Increase, decrease, protect, help.', [
        ['steigen', 'shty-gen', 'to increase / rise'],
        ['sinken', 'zing-ken', 'to decrease / sink'],
        ['treffen', 'tref-fen', 'to meet / hit'],
        ['fliehen', 'flee-en', 'to flee'],
        ['schützen', 'shüts-en', 'to protect'],
        ['fortschreiten', 'fort-shry-ten', 'to advance'],
        ['zurückkehren', 'tsoo-rück-kair-en', 'to return'],
        ['sich trennen', 'zikh tren-nen', 'to separate'],
        ['sammeln', 'zah-meln', 'to gather / collect'],
        ['mitteilen', 'mit-tye-len', 'to inform / convey'],
      ]),
      pack('b1-6', 'Stage 6 · Everyday B1', 'Convenient, serious, recently, limit.', [
        ['praktisch', 'prak-tish', 'practical / convenient'],
        ['unpraktisch', 'oon-prak-tish', 'impractical'],
        ['ernst', 'ernst', 'serious'],
        ['neulich', 'noy-likh', 'recently'],
        ['die Zukunft', 'dee tsoo-koonft', 'future'],
        ['gewöhnlich', 'ge-vöhn-likh', 'usual / ordinary'],
        ['besonders', 'be-zon-ders', 'especially'],
        ['mindestens', 'min-des-tens', 'at least'],
        ['begrenzen', 'be-grents-en', 'to limit'],
        ['selbstverständlich', 'zelbst-fer-shtent-likh', 'obvious / of course'],
      ]),
      pack('b1-7', 'Stage 7 · Connectors', 'However, therefore, if, for example.', [
        ['die Verantwortung', 'dee fer-ant-vor-toong', 'responsibility'],
        ['die Gewohnheit', 'dee ge-vohn-hite', 'habit / custom'],
        ['das Detail', 'dahs de-tie', 'detail'],
        ['ähnlich', 'ähn-likh', 'similar'],
        ['zum Beispiel', 'tsoom by-shpeel', 'for example'],
        ['das heißt', 'dahs hyst', 'that is / in other words'],
        ['jedoch', 'yay-dokh', 'however'],
        ['außerdem', 'ows-er-dem', 'besides / furthermore'],
        ['deshalb', 'des-halp', 'therefore'],
        ['wenn', 'ven', 'if / when'],
      ]),
      mix('b1-mix', 'Stage 8 · B1 mixed review'),
    ],
  },
  b2: {
    id: 'b2',
    label: 'B2 words',
    kicker: 'CEFR · Independent',
    blurb: 'Vantage German: argument, workplace precision, and abstract nouns (Goethe-B2 style).',
    kind: 'vocab',
    group: 'words',
    stages: [
      pack(
        'b2-0',
        'Stage 0 · First B2',
        'Six words for clear argument. Learn them, then tap A–F.',
        [
          ['der Standpunkt', 'der shtant-poonkt', 'point of view'],
          ['die Auseinandersetzung', 'dee ow-sye-nan-der-zet-soong', 'debate / dispute'],
          ['nachvollziehen', 'nahkh-fol-tsee-en', 'to follow / understand (an argument)'],
          ['maßgeblich', 'mahs-gabe-likh', 'decisive / authoritative'],
          ['die Voraussetzung', 'dee for-owss-zet-soong', 'prerequisite'],
          ['erfordern', 'er-for-dern', 'to require'],
        ],
        { intro: true }
      ),
      pack('b2-1', 'Stage 1 · Argument', 'Claim, evidence, concede, refute.', [
        ['die Behauptung', 'dee be-howp-toong', 'claim / assertion'],
        ['das Argument', 'dahs ar-goo-ment', 'argument'],
        ['der Beweis', 'der be-vice', 'proof / evidence'],
        ['widerlegen', 'vee-der-lay-gen', 'to refute'],
        ['einräumen', 'ine-roy-men', 'to concede'],
        ['betonen', 'be-toh-nen', 'to emphasize'],
        ['darlegen', 'dahr-lay-gen', 'to set out / explain'],
        ['folgerichtig', 'fol-ge-rikh-tikh', 'logical / consistent'],
        ['zweifelhaft', 'tsvy-fel-hahft', 'doubtful'],
        ['überzeugend', 'ü-ber-tsoy-gent', 'convincing'],
      ]),
      pack('b2-2', 'Stage 2 · Workplace', 'Deadline, efficiency, stakeholder, brief.', [
        ['die Frist', 'dee frist', 'deadline / time limit'],
        ['die Effizienz', 'dee eh-fee-tsyents', 'efficiency'],
        ['die Zuständigkeit', 'dee tsoo-shten-dikh-kite', 'responsibility / remit'],
        ['die Absprache', 'dee ap-shprah-khuh', 'agreement / briefing'],
        ['die Rückmeldung', 'dee rük-meld-oong', 'feedback'],
        ['die Priorität', 'dee pree-o-ree-tait', 'priority'],
        ['vertreten', 'fer-tray-ten', 'to represent'],
        ['koordinieren', 'ko-or-dee-nee-ren', 'to coordinate'],
        ['gewährleisten', 'ge-vair-ly-sten', 'to ensure / guarantee'],
        ['überarbeiten', 'ü-ber-ar-by-ten', 'to revise'],
      ]),
      pack('b2-3', 'Stage 3 · Abstract nouns', 'Extent, tendency, framework, issue.', [
        ['das Ausmaß', 'dahs ows-mahs', 'extent / scale'],
        ['die Tendenz', 'dee ten-dents', 'tendency'],
        ['der Rahmen', 'der rah-men', 'framework'],
        ['die Angelegenheit', 'dee an-ge-lay-gen-hite', 'matter / issue'],
        ['der Aspekt', 'der as-pekt', 'aspect'],
        ['die Perspektive', 'dee per-spek-tee-vuh', 'perspective'],
        ['der Zusammenhang', 'der tsoo-zahm-en-hahng', 'connection / context'],
        ['die Auswirkung', 'dee ows-vir-koong', 'effect / impact'],
        ['die Herausforderung', 'dee her-ows-for-de-roong', 'challenge'],
        ['die Maßnahme', 'dee mahs-nah-muh', 'measure / action'],
      ]),
      pack('b2-4', 'Stage 4 · Precise verbs', 'Imply, distinguish, maintain, restrict.', [
        ['andeuten', 'an-doy-ten', 'to imply / hint'],
        ['unterscheiden', 'oon-ter-shy-den', 'to distinguish'],
        ['beibehalten', 'by-be-hal-ten', 'to maintain / keep'],
        ['einschränken', 'ine-shrenk-en', 'to restrict'],
        ['beitragen', 'by-trah-gen', 'to contribute'],
        ['hervorheben', 'her-for-hay-ben', 'to highlight'],
        ['zurückweisen', 'tsoo-rück-vy-zen', 'to reject'],
        ['überwinden', 'ü-ber-vin-den', 'to overcome'],
        ['vermeiden', 'fer-my-den', 'to avoid'],
        ['ermöglichen', 'er-mög-likh-en', 'to make possible'],
      ]),
      pack('b2-5', 'Stage 5 · Stance', 'Although, whereas, provided that.', [
        ['obwohl', 'op-vohl', 'although'],
        ['während', 'vair-end', 'while / whereas'],
        ['sofern', 'zo-fern', 'provided that'],
        ['dennoch', 'den-nokh', 'nevertheless'],
        ['insofern', 'in-zo-fern', 'in that respect'],
        ['angesichts', 'an-ge-zikhts', 'in view of'],
        ['hinsichtlich', 'hin-zikht-likh', 'with regard to'],
        ['im Gegensatz zu', 'im gay-gen-zahts tsoo', 'in contrast to'],
        ['einerseits', 'ine-er-zyts', 'on the one hand'],
        ['andererseits', 'an-de-rer-zyts', 'on the other hand'],
      ]),
      pack('b2-6', 'Stage 6 · Public life', 'Law, media, research, citizen.', [
        ['das Gesetz', 'dahs ge-zets', 'law'],
        ['die Öffentlichkeit', 'dee öf-ent-likh-kite', 'the public'],
        ['die Forschung', 'dee for-shoong', 'research'],
        ['der Bürger', 'der bür-ger', 'citizen'],
        ['die Behörde', 'dee be-hör-duh', 'authority / agency'],
        ['die Richtlinie', 'dee rikht-lee-nuh', 'guideline / directive'],
        ['die Umfrage', 'dee oom-frah-guh', 'survey'],
        ['die Berichterstattung', 'dee be-rikh-ter-shta-toong', 'news coverage'],
        ['die Nachhaltigkeit', 'dee nahkh-hal-tikh-kite', 'sustainability'],
        ['die Gleichberechtigung', 'dee glykh-be-rekh-tee-goong', 'equal rights'],
      ]),
      mix('b2-mix', 'Stage 7 · B2 mixed review'),
    ],
  },
  c1: {
    id: 'c1',
    label: 'C1 words',
    kicker: 'CEFR · Proficient',
    blurb: 'Effective operational proficiency: register, nuance, and academic / professional lexis.',
    kind: 'vocab',
    group: 'words',
    stages: [
      pack(
        'c1-0',
        'Stage 0 · First C1',
        'Six high-register words. See the German, the sound, and the English, then A–F.',
        [
          ['überwiegend', 'ü-ber-vee-gent', 'predominantly'],
          ['die Auseinandersetzung', 'dee ow-sye-nan-der-zet-soong', 'critical engagement / debate'],
          ['implizieren', 'im-plee-tsee-ren', 'to imply'],
          ['die Tragweite', 'dee trahk-vy-tuh', 'implications / scope'],
          ['differenziert', 'dif-fe-ren-tseert', 'nuanced / differentiated'],
          ['der Diskurs', 'der dis-koors', 'discourse'],
        ],
        { intro: true }
      ),
      pack('c1-1', 'Stage 1 · Academic', 'Thesis, source, findings, caveat.', [
        ['die These', 'dee tay-zuh', 'thesis / claim'],
        ['die Quelle', 'dee kvel-uh', 'source'],
        ['die Erkenntnis', 'dee er-kent-niss', 'finding / insight'],
        ['der Vorbehalt', 'der for-be-halt', 'reservation / caveat'],
        ['die Herangehensweise', 'dee her-an-gay-ens-vy-zuh', 'approach'],
        ['die Schlussfolgerung', 'dee shlooss-fol-ge-roong', 'conclusion'],
        ['belegen', 'be-lay-gen', 'to substantiate / cite'],
        ['hinterfragen', 'hin-ter-frah-gen', 'to question critically'],
        ['einordnen', 'ine-ord-nen', 'to contextualize / classify'],
        ['zugrunde liegen', 'tsoo-groon-duh lee-gen', 'to underlie'],
      ]),
      pack('c1-2', 'Stage 2 · Precision', 'Subtle, inherent, negligible, marked.', [
        ['subtil', 'zoop-teel', 'subtle'],
        ['innewohnend', 'in-ne-voh-nend', 'inherent'],
        ['geringfügig', 'ge-ring-fü-gikh', 'negligible / minor'],
        ['ausgeprägt', 'ows-ge-praykt', 'pronounced / marked'],
        ['ambivalent', 'am-bee-vah-lent', 'ambivalent'],
        ['kohärent', 'ko-hair-ent', 'coherent'],
        ['widersprüchlich', 'vee-der-shprükh-likh', 'contradictory'],
        ['plausibel', 'plow-zee-bel', 'plausible'],
        ['fragwürdig', 'frahk-vür-dikh', 'questionable'],
        ['zwingend', 'tsving-ent', 'compelling / conclusive'],
      ]),
      pack('c1-3', 'Stage 3 · Formal verbs', 'Constitute, entail, refrain, attribute.', [
        ['darstellen', 'dahr-shtel-len', 'to constitute / represent'],
        ['nach sich ziehen', 'nahkh zikh tsee-en', 'to entail'],
        ['absehen von', 'ap-zay-en fon', 'to refrain from'],
        ['zuschreiben', 'tsoo-shry-ben', 'to attribute'],
        ['hervorgehen aus', 'her-for-gay-en ows', 'to emerge from'],
        ['einhergehen mit', 'ine-hair-gay-en mit', 'to go hand in hand with'],
        ['berücksichtigen', 'be-rück-zikh-tee-gen', 'to take into account'],
        ['gewichten', 'ge-vikh-ten', 'to weigh / prioritize'],
        ['relativieren', 're-lah-tee-vee-ren', 'to put into perspective'],
        ['thematisieren', 'te-mah-tee-zee-ren', 'to address / raise as a topic'],
      ]),
      pack('c1-4', 'Stage 4 · Discourse', 'Admittedly, nonetheless, insofar as.', [
        ['zugegebenermaßen', 'tsoo-ge-gay-be-ner-mah-sen', 'admittedly'],
        ['nichtsdestotrotz', 'nikhts-des-to-trotz', 'nonetheless'],
        ['insofern als', 'in-zo-fern ahls', 'insofar as'],
        ['wenngleich', 'ven-glykh', 'even though'],
        ['gleichwohl', 'glykh-vohl', 'nevertheless'],
        ['mithin', 'mit-hin', 'hence / consequently'],
        ['überdies', 'ü-ber-dees', 'moreover'],
        ['demzufolge', 'dem-tsoo-fol-guh', 'accordingly'],
        ['unbeschadet', 'oon-be-shah-det', 'without prejudice to'],
        ['im Wesentlichen', 'im vay-zent-likh-en', 'essentially'],
      ]),
      pack('c1-5', 'Stage 5 · Public register', 'Ordinance, stakeholder, disparity.', [
        ['die Verordnung', 'dee fer-ord-noong', 'ordinance / regulation'],
        ['der Interessenträger', 'der in-te-ress-en-tray-ger', 'stakeholder'],
        ['das Gefälle', 'dahs ge-fel-uh', 'disparity / gradient'],
        ['die Tragfähigkeit', 'dee trahk-fay-ikh-kite', 'viability / carrying capacity'],
        ['die Leitlinie', 'dee lite-lee-nuh', 'guiding principle'],
        ['die Rechenschaft', 'dee rekh-en-shahft', 'accountability'],
        ['die Ermessensspielraum', 'dee er-mess-ens-shpeel-rowm', 'discretion / leeway'],
        ['die Folgewirkung', 'dee fol-ge-vir-koong', 'knock-on effect'],
        ['die Interessenabwägung', 'dee in-te-ress-en-ap-vay-goong', 'balancing of interests'],
        ['die Sachlage', 'dee zahkh-lah-guh', 'state of affairs'],
      ]),
      mix('c1-mix', 'Stage 6 · C1 mixed review'),
    ],
  },
  c2: {
    id: 'c2',
    label: 'C2 words',
    kicker: 'CEFR · Proficient',
    blurb: 'Mastery: fine distinctions, collocations, and high-register verbs (Goethe-C2 style).',
    kind: 'vocab',
    group: 'words',
    stages: [
      pack(
        'c2-0',
        'Stage 0 · First C2',
        'Six mastery-level words. Learn the exact German form, then tap A–F.',
        [
          ['ohnehin', 'oh-ne-hin', 'anyway / in any case'],
          ['desavouieren', 'de-za-voo-ee-ren', 'to disavow / undercut'],
          ['die Unwägbarkeit', 'dee oon-vayk-bahr-kite', 'imponderable / uncertainty'],
          ['anheimstellen', 'an-hime-shtel-len', 'to leave to someone’s discretion'],
          ['idiosynkratisch', 'ee-dee-o-zün-krah-tish', 'idiosyncratic'],
          ['die Feinabstimmung', 'dee fine-ap-shtim-oong', 'fine-tuning'],
        ],
        { intro: true }
      ),
      pack('c2-1', 'Stage 1 · Fine verbs', 'Glean, gloss over, forestall, evince.', [
        ['entnehmen', 'ent-nay-men', 'to glean / infer (from)'],
        ['beschönigen', 'be-shö-nee-gen', 'to gloss over / sugarcoat'],
        ['zuvorkommen', 'tsoo-for-kom-men', 'to forestall / anticipate'],
        ['erkennen lassen', 'er-ken-nen lahss-en', 'to evince / make apparent'],
        ['nahelegen', 'nah-uh-lay-gen', 'to suggest (strongly)'],
        ['geltend machen', 'gel-tent makh-en', 'to assert / claim (a right)'],
        ['in Abrede stellen', 'in ap-ray-duh shtel-len', 'to deny / dispute'],
        ['zu Gehör bringen', 'tsoo ge-hör bring-en', 'to give voice to'],
        ['ins Feld führen', 'ins felt fü-ren', 'to adduce / put forward'],
        ['einer Prüfung unterziehen', 'ine-er prü-foong oon-ter-tsee-en', 'to subject to scrutiny'],
      ]),
      pack('c2-2', 'Stage 2 · Collocations', 'Fixed high-register pairings.', [
        ['schwerwiegende Folgen', 'shvair-vee-gen-duh fol-gen', 'grave consequences'],
        ['im Einklang mit', 'im ine-klahng mit', 'in keeping with'],
        ['Anstoß erregen', 'an-shtoess er-ray-gen', 'to cause offence'],
        ['zur Sprache bringen', 'tsoor shprah-khuh bring-en', 'to bring up / raise'],
        ['in Betracht ziehen', 'in be-trakht tsee-en', 'to take into consideration'],
        ['Rechenschaft ablegen', 'rekh-en-shahft ap-lay-gen', 'to give an account'],
        ['den Ausschlag geben', 'den ows-shlahk gay-ben', 'to be the deciding factor'],
        ['einer Sache Rechnung tragen', 'ine-er zah-khuh rekh-noong trah-gen', 'to take something into account'],
        ['im Widerspruch stehen', 'im vee-der-shprookh shtay-en', 'to be at odds with'],
        ['ohne Wenn und Aber', 'oh-nuh ven oont ah-ber', 'without ifs or buts'],
      ]),
      pack('c2-3', 'Stage 3 · Nuance adjectives', 'Telling, tenuous, sweeping, apt.', [
        ['aufschlussreich', 'owf-shlooss-rykh', 'telling / revealing'],
        ['dünn', 'dün', 'tenuous (of an argument)'],
        ['pauschal', 'pow-shahl', 'sweeping / blanket'],
        ['treffend', 'tref-fent', 'apt / pertinent'],
        ['abwegig', 'ap-vay-gikh', 'far-fetched'],
        ['unzutreffend', 'oon-tsoo-tref-fent', 'inaccurate / unfounded'],
        ['sachdienlich', 'zahkh-deen-likh', 'conducive / relevant to the matter'],
        ['unmissverständlich', 'oon-miss-fer-shtent-likh', 'unequivocal'],
        ['hintergründig', 'hin-ter-grün-dikh', 'subtle / with hidden depth'],
        ['emphatisch', 'em-fah-tish', 'emphatic'],
      ]),
      pack('c2-4', 'Stage 4 · Style markers', 'Adverbs that shift register.', [
        ['freilich', 'fry-likh', 'admittedly / to be sure'],
        ['allenthalben', 'ah-len-thal-ben', 'everywhere / on all sides'],
        ['vollends', 'fol-lents', 'entirely / utterly'],
        ['über Gebühr', 'ü-ber ge-bür', 'unduly / excessively'],
        ['gleichsam', 'glykh-zahm', 'as it were / so to speak'],
        ['gewissermaßen', 'ge-viss-er-mah-sen', 'in a manner of speaking'],
        ['unversehens', 'oon-fer-zay-ens', 'unexpectedly'],
        ['mithin', 'mit-hin', 'thus / therefore (formal)'],
        ['denn auch', 'den owkh', 'and indeed / as might be expected'],
        ['kaum dass', 'kowm dahs', 'hardly had / no sooner'],
      ]),
      pack('c2-5', 'Stage 5 · Rare but useful', 'Words a C2 reader is expected to know.', [
        ['die Gretchenfrage', 'dee gretch-en-frah-guh', 'the crucial / awkward question'],
        ['der Stein des Anstoßes', 'der shtine des an-shtoess-es', 'the bone of contention'],
        ['die Crux', 'dee krooks', 'the crux'],
        ['das Menetekel', 'dahs me-ne-tay-kel', 'warning sign / writing on the wall'],
        ['die Quadratur des Kreises', 'dee kvah-drah-toor des kry-zes', 'squaring the circle'],
        ['der rote Faden', 'der roh-tuh fah-den', 'the common thread'],
        ['die Spitze des Eisbergs', 'dee shpit-suh des ice-bairks', 'the tip of the iceberg'],
        ['ein Tropfen auf den heißen Stein', 'ine trop-fen owf den hy-sen shtine', 'a drop in the ocean'],
        ['das Zünglein an der Waage', 'dahs tsüng-line an der vah-guh', 'the tipping factor'],
        ['der springende Punkt', 'der shpring-en-duh poonkt', 'the crucial point'],
      ]),
      mix('c2-mix', 'Stage 6 · C2 mixed review'),
    ],
  },
};
